#include "subprograms.h"
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
void a (void);
void mymodel__s1 (void)
{

  a ();
}

void b (void);
void mymodel__s2 (void)
{

  b ();
}


