#include <activity.h>
#include "subprograms.h"
#include <po_hi_task.h>
#include <po_hi_main.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Working Copy from rc4001793*/
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
void __po_hi_main_initialize (void);

/*!
 * \fn void* task1_job (void)
 * \brief Function executed by the task task1
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : Task1*/
void* task1_job (void)
{

  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (this_process_task1_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (this_process_task1_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /*  Call implementation*/
    sr_system__s1 ();
    __po_hi_wait_for_next_period (this_process_task1_k);
  }
}


/*!
 * \fn void* task2_job (void)
 * \brief Function executed by the task task2
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : Task2*/
void* task2_job (void)
{

  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (this_process_task2_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (this_process_task2_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /*  Call implementation*/
    sr_system__s2 ();
    __po_hi_wait_for_next_period (this_process_task2_k);
  }
}


