#include <deployment.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Working Copy from rc4001793*/
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
__po_hi_node_t __po_hi_mynode = this_process_k;

