/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Working Copy from rc4001793*/
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/

