#include "subprograms.h"
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Working Copy from rc4001793*/
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
void apply_break (void);
void sr_system__s1 (void)
{

  apply_break ();
}

void acceleration (void);
void sr_system__s2 (void)
{

  acceleration ();
}


