#ifndef __OCARINA_GENERATED_SUBPROGRAMS_H_
#define __OCARINA_GENERATED_SUBPROGRAMS_H_ 
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Working Copy from rc4001793*/

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

void sr_system__s1 (void);

void sr_system__s2 (void);

#endif
